; PlatformIO config for B4B IMU Combat Firmware
; ESP32 + ISM330DHCX + DRV8871 motor drivers

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    sparkfun/SparkFun 6DoF ISM330DHCX@^1.0.5
    ESP Async WebServer
upload_speed = 921600

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_RUNNING_CORE=1
